import { LearningPath, RoomDefinition } from "./types";

export const learningPaths: { name: LearningPath; description: string; accent: string }[] = [
  {
    name: "Linux Basics",
    description: "A complete beginner foundation: navigation, files, text, search, permissions, processes, streams, and identity.",
    accent: "Foundation",
  },
  {
    name: "Linux for Cybersecurity",
    description: "Apply Linux fluency to hardening, log analysis, SUID review, process response, network triage, and persistence hunting.",
    accent: "Defender path",
  },
  {
    name: "Incident Response",
    description: "Correlate evidence and contain a simulated Linux compromise in a capstone room.",
    accent: "Capstone",
  },
];

export const rooms: RoomDefinition[] = [
  {
    slug: "basic-navigation",
    title: "Navigation Essentials",
    subtitle: "Linux Basics · Room 1",
    description: "Learn where you are, what is around you, and how to move through Linux directories using absolute and relative paths.",
    path: "Linux Basics",
    difficulty: "Easy",
    duration: "15 min",
    icon: "terminal",
    tags: ["pwd", "ls -la", "cd", "paths"],
    learning: ["Print the current directory", "List normal and hidden entries", "Use absolute and relative paths", "Return home with ~"],
    badge: "Terminal Explorer",
    tasks: [
      {
        id: "nav-1",
        title: "Find your bearings",
        objective: "Print your current working directory.",
        context: "Every investigation starts by understanding shell context. Confirm where the analyst account landed.",
        hint: "Use pwd.",
        xp: 50,
        check: { type: "command-ran", command: "pwd" },
      },
      {
        id: "nav-2",
        title: "List everything",
        objective: "List /home/analyst with a long listing that includes hidden entries.",
        context: "Attackers often hide artifacts with dot-prefixed names. Learn to request metadata and hidden entries together.",
        hint: "Use ls -la /home/analyst.",
        xp: 75,
        check: { type: "history-contains", fragments: ["ls", "-la", "/home/analyst"] },
      },
      {
        id: "nav-3",
        title: "Move with an absolute path",
        objective: "Change directory to /home/analyst/training/logs.",
        context: "The training logs are several directories away. Use a full absolute path so the destination is unambiguous.",
        hint: "cd /home/analyst/training/logs",
        xp: 75,
        check: { type: "cwd", path: "/home/analyst/training/logs" },
      },
      {
        id: "nav-4",
        title: "Move to the parent",
        objective: "Use cd .. and finish in /home/analyst/training.",
        context: "Relative navigation is faster when moving around nearby evidence directories.",
        hint: "From logs, run cd ..",
        xp: 75,
        check: { type: "all", checks: [
          { type: "cwd", path: "/home/analyst/training" },
          { type: "history-contains", fragments: ["cd", ".."] },
        ] },
      },
      {
        id: "nav-5",
        title: "Return home",
        objective: "Use ~ to return to /home/analyst.",
        context: "The tilde is a standard shortcut for the current user's home directory.",
        hint: "Run cd ~",
        xp: 50,
        check: { type: "all", checks: [
          { type: "cwd", path: "/home/analyst" },
          { type: "history-contains", fragments: ["cd", "~"] },
        ] },
      },
    ],
  },
  {
    slug: "basic-files",
    title: "Files & Directories",
    subtitle: "Linux Basics · Room 2",
    description: "Create, copy, rename, move, and remove files so later security tasks feel natural instead of memorized.",
    path: "Linux Basics",
    difficulty: "Easy",
    duration: "20 min",
    icon: "file",
    tags: ["mkdir", "touch", "cp", "mv", "rm"],
    learning: ["Create directories and empty files", "Copy evidence safely", "Rename and move files", "Delete files intentionally"],
    prerequisites: ["basic-navigation"],
    tasks: [
      {
        id: "files-1",
        title: "Create a workspace",
        objective: "Create /home/analyst/lab.",
        context: "Analysts should separate working copies from original evidence. Create a dedicated lab directory.",
        hint: "mkdir /home/analyst/lab",
        xp: 75,
        check: { type: "file-exists", path: "/home/analyst/lab" },
      },
      {
        id: "files-2",
        title: "Create case notes",
        objective: "Create an empty file /home/analyst/lab/incident.txt.",
        context: "Create a placeholder for your investigation notes without opening an editor.",
        hint: "touch /home/analyst/lab/incident.txt",
        xp: 75,
        check: { type: "file-exists", path: "/home/analyst/lab/incident.txt" },
      },
      {
        id: "files-3",
        title: "Copy reference material",
        objective: "Copy training/notes.txt to /home/analyst/lab/notes-copy.txt.",
        context: "Make a working copy instead of modifying the source reference file.",
        hint: "cp /home/analyst/training/notes.txt /home/analyst/lab/notes-copy.txt",
        xp: 100,
        check: { type: "file-exists", path: "/home/analyst/lab/notes-copy.txt" },
      },
      {
        id: "files-4",
        title: "Rename the notes file",
        objective: "Rename incident.txt to case-notes.txt.",
        context: "mv is used for both moving and renaming files in Linux.",
        hint: "mv /home/analyst/lab/incident.txt /home/analyst/lab/case-notes.txt",
        xp: 100,
        check: { type: "file-exists", path: "/home/analyst/lab/case-notes.txt" },
      },
      {
        id: "files-5",
        title: "Remove the disposable copy",
        objective: "Delete /home/analyst/lab/notes-copy.txt.",
        context: "Practice deliberate deletion on a disposable copy, not on original evidence.",
        hint: "rm /home/analyst/lab/notes-copy.txt",
        xp: 100,
        check: { type: "all", checks: [
          { type: "history-contains", fragments: ["rm", "notes-copy.txt"] },
          { type: "file-not-exists", path: "/home/analyst/lab/notes-copy.txt" },
        ] },
      },
    ],
  },
  {
    slug: "basic-reading",
    title: "Reading Text Files",
    subtitle: "Linux Basics · Room 3",
    description: "Inspect small and large text files using cat, head, tail, and less—the everyday toolkit for configuration and log review.",
    path: "Linux Basics",
    difficulty: "Easy",
    duration: "15 min",
    icon: "file",
    tags: ["cat", "head", "tail", "less"],
    learning: ["Read a complete file", "Inspect the first lines", "Inspect the newest tail lines", "Use a pager-style command"],
    prerequisites: ["basic-files"],
    tasks: [
      {
        id: "read-1",
        title: "Read the checklist",
        objective: "Display /home/analyst/training/notes.txt with cat.",
        context: "cat is convenient for small files and quick configuration checks.",
        hint: "cat /home/analyst/training/notes.txt",
        xp: 50,
        check: { type: "history-contains", fragments: ["cat", "training/notes.txt"] },
      },
      {
        id: "read-2",
        title: "Inspect the beginning",
        objective: "Use head on access.log.",
        context: "When files are large, start with a limited view instead of dumping everything to the terminal.",
        hint: "head /home/analyst/training/logs/access.log",
        xp: 75,
        check: { type: "history-contains", fragments: ["head", "access.log"] },
      },
      {
        id: "read-3",
        title: "Inspect the latest entries",
        objective: "Use tail on access.log.",
        context: "tail is especially useful for checking recent log events.",
        hint: "tail /home/analyst/training/logs/access.log",
        xp: 75,
        check: { type: "history-contains", fragments: ["tail", "access.log"] },
      },
      {
        id: "read-4",
        title: "Open with less",
        objective: "Inspect notes.txt using less.",
        context: "On a real host, less provides a pager for navigating long text. The simulator returns the content directly while preserving the command habit.",
        hint: "less /home/analyst/training/notes.txt",
        xp: 75,
        check: { type: "history-contains", fragments: ["less", "notes.txt"] },
      },
    ],
  },
  {
    slug: "basic-search",
    title: "Search & Filtering",
    subtitle: "Linux Basics · Room 4",
    description: "Find useful lines and files with grep and find, including line numbers, case-insensitive matches, and wildcard names.",
    path: "Linux Basics",
    difficulty: "Easy",
    duration: "20 min",
    icon: "search",
    tags: ["grep", "grep -n", "find", "wildcards"],
    learning: ["Search file contents", "Display matching line numbers", "Search recursively by filename", "Use wildcard patterns"],
    prerequisites: ["basic-reading"],
    tasks: [
      {
        id: "search-1",
        title: "Find errors",
        objective: "Search access.log for ERROR.",
        context: "Filtering is more efficient than reading a busy log line by line.",
        hint: "grep ERROR /home/analyst/training/logs/access.log",
        xp: 75,
        check: { type: "history-contains", fragments: ["grep", "ERROR", "access.log"] },
      },
      {
        id: "search-2",
        title: "Add line numbers",
        objective: "Use grep -n to search access.log for ERROR.",
        context: "Line numbers make findings easier to communicate and revisit.",
        hint: "grep -n ERROR /home/analyst/training/logs/access.log",
        xp: 100,
        check: { type: "history-contains", fragments: ["grep", "-n", "ERROR", "access.log"] },
      },
      {
        id: "search-3",
        title: "Find a script by name",
        objective: "Use find under /home/analyst/training to locate deploy.sh.",
        context: "find is essential when the location of an artifact is unknown.",
        hint: "find /home/analyst/training -name deploy.sh",
        xp: 100,
        check: { type: "history-contains", fragments: ["find", "/home/analyst/training", "-name", "deploy.sh"] },
      },
      {
        id: "search-4",
        title: "Find all logs",
        objective: "Use find with a *.log name pattern under /home/analyst/training.",
        context: "Wildcard patterns help enumerate groups of similarly named files.",
        hint: "find /home/analyst/training -name '*.log'",
        xp: 100,
        check: { type: "history-contains", fragments: ["find", "/home/analyst/training", "-name", "*.log"] },
      },
    ],
  },
  {
    slug: "basic-permissions",
    title: "Linux Permissions",
    subtitle: "Linux Basics · Room 5",
    description: "Understand rwx bits, symbolic chmod, and numeric modes before moving on to security hardening.",
    path: "Linux Basics",
    difficulty: "Easy",
    duration: "20 min",
    icon: "shield",
    tags: ["ls -l", "rwx", "chmod +x", "chmod 600"],
    learning: ["Interpret long-listing permissions", "Make a script executable", "Use numeric permission modes", "Verify final metadata"],
    prerequisites: ["basic-search"],
    tasks: [
      {
        id: "bperm-1",
        title: "Inspect a script",
        objective: "Use ls -l on /home/analyst/training/scripts/deploy.sh.",
        context: "Before changing permissions, establish the current state.",
        hint: "ls -l /home/analyst/training/scripts/deploy.sh",
        xp: 75,
        check: { type: "history-contains", fragments: ["ls", "-l", "deploy.sh"] },
      },
      {
        id: "bperm-2",
        title: "Make it executable",
        objective: "Add execute permission with chmod +x to deploy.sh.",
        context: "Symbolic chmod is readable and useful when you want to add or remove a specific capability.",
        hint: "chmod +x /home/analyst/training/scripts/deploy.sh",
        xp: 125,
        check: { type: "all", checks: [
          { type: "history-contains", fragments: ["chmod", "+x", "deploy.sh"] },
          { type: "file-mode", path: "/home/analyst/training/scripts/deploy.sh", mode: 0o755 },
        ] },
      },
      {
        id: "bperm-3",
        title: "Protect a secret",
        objective: "Set /home/analyst/training/secret.key to mode 600.",
        context: "A private key should not be readable by group or other users in this exercise.",
        hint: "chmod 600 /home/analyst/training/secret.key",
        xp: 125,
        check: { type: "file-mode", path: "/home/analyst/training/secret.key", mode: 0o600 },
      },
      {
        id: "bperm-4",
        title: "Verify the result",
        objective: "Run stat on secret.key after hardening it.",
        context: "Never assume a security change succeeded; verify the final state.",
        hint: "stat /home/analyst/training/secret.key",
        xp: 75,
        check: { type: "history-contains", fragments: ["stat", "secret.key"] },
      },
    ],
  },
  {
    slug: "basic-processes",
    title: "Processes & PIDs",
    subtitle: "Linux Basics · Room 6",
    description: "Read the process table, understand PIDs, and use a pipeline to isolate a process without taking destructive action.",
    path: "Linux Basics",
    difficulty: "Easy",
    duration: "15 min",
    icon: "activity",
    tags: ["ps", "ps aux", "PID", "grep"],
    learning: ["List processes", "Recognize process owners and PIDs", "Filter a process list", "Prepare for safe containment"],
    prerequisites: ["basic-permissions"],
    tasks: [
      {
        id: "bproc-1",
        title: "List processes",
        objective: "Run ps.",
        context: "Processes are active programs. Start with the basic process command.",
        hint: "ps",
        xp: 50,
        check: { type: "command-ran", command: "ps" },
      },
      {
        id: "bproc-2",
        title: "Expand the view",
        objective: "Run ps aux.",
        context: "The common aux form exposes owners, PIDs, resource usage, and command lines.",
        hint: "ps aux",
        xp: 75,
        check: { type: "history-contains", fragments: ["ps", "aux"] },
      },
      {
        id: "bproc-3",
        title: "Find SSH",
        objective: "Filter ps aux for sshd using a pipe and grep.",
        context: "Pipelines let the output of one command become the input to another.",
        hint: "ps aux | grep sshd",
        xp: 100,
        check: { type: "history-contains", fragments: ["ps", "aux", "|", "grep", "sshd"] },
      },
    ],
  },
  {
    slug: "basic-streams",
    title: "Pipes & Redirection",
    subtitle: "Linux Basics · Room 7",
    description: "Connect commands and persist terminal output using pipes, overwrite redirection, append redirection, and tee.",
    path: "Linux Basics",
    difficulty: "Easy",
    duration: "20 min",
    icon: "terminal",
    tags: ["|", ">", ">>", "tee"],
    learning: ["Pipe output between commands", "Write output with >", "Append with >>", "Write and display with tee"],
    prerequisites: ["basic-processes"],
    tasks: [
      {
        id: "stream-1",
        title: "Pipe log output",
        objective: "Pipe cat access.log into grep ERROR.",
        context: "The pipe is one of the most important shell composition tools for investigation workflows.",
        hint: "cat /home/analyst/training/logs/access.log | grep ERROR",
        xp: 100,
        check: { type: "history-contains", fragments: ["cat", "access.log", "|", "grep", "ERROR"] },
      },
      {
        id: "stream-2",
        title: "Create a report",
        objective: "Use > to write the text CASE-OPENED into /home/analyst/report.txt.",
        context: "Redirection lets you capture command output in a file.",
        hint: "echo CASE-OPENED > /home/analyst/report.txt",
        xp: 125,
        check: { type: "file-content-contains", path: "/home/analyst/report.txt", text: "CASE-OPENED" },
      },
      {
        id: "stream-3",
        title: "Append a finding",
        objective: "Use >> to append IOC-REVIEWED to /home/analyst/report.txt.",
        context: "Append redirection preserves existing content instead of replacing it.",
        hint: "echo IOC-REVIEWED >> /home/analyst/report.txt",
        xp: 125,
        check: { type: "all", checks: [
          { type: "history-contains", fragments: [">>", "report.txt"] },
          { type: "file-content-contains", path: "/home/analyst/report.txt", text: "IOC-REVIEWED" },
        ] },
      },
      {
        id: "stream-4",
        title: "Write with tee",
        objective: "Pipe echo VERIFIED into tee /home/analyst/verified.txt.",
        context: "tee is useful when you want output on screen and in a file at the same time.",
        hint: "echo VERIFIED | tee /home/analyst/verified.txt",
        xp: 125,
        check: { type: "file-content-contains", path: "/home/analyst/verified.txt", text: "VERIFIED" },
      },
    ],
  },
  {
    slug: "basic-identity",
    title: "Users & System Context",
    subtitle: "Linux Basics · Room 8",
    description: "Identify the current user, group memberships, hostname, operating system, and command history before entering the defender path.",
    path: "Linux Basics",
    difficulty: "Easy",
    duration: "15 min",
    icon: "terminal",
    tags: ["whoami", "id", "groups", "uname"],
    learning: ["Identify the active user", "Inspect group membership", "Identify the host", "Review system and shell history"],
    prerequisites: ["basic-streams"],
    badge: "Linux Fundamentals",
    tasks: [
      {
        id: "identity-1",
        title: "Who are you?",
        objective: "Run whoami and id.",
        context: "Security decisions depend on the identity and privileges of the current account.",
        hint: "Run whoami, then id.",
        xp: 75,
        check: { type: "all", checks: [
          { type: "command-ran", command: "whoami" },
          { type: "command-ran", command: "id" },
        ] },
      },
      {
        id: "identity-2",
        title: "Inspect groups",
        objective: "Run groups.",
        context: "Group membership can grant access to logs, devices, and administration capabilities.",
        hint: "groups",
        xp: 50,
        check: { type: "command-ran", command: "groups" },
      },
      {
        id: "identity-3",
        title: "Identify the host",
        objective: "Run hostname and uname -a.",
        context: "Host identity and kernel context are standard facts to capture during triage.",
        hint: "Run hostname, then uname -a.",
        xp: 100,
        check: { type: "all", checks: [
          { type: "command-ran", command: "hostname" },
          { type: "history-contains", fragments: ["uname", "-a"] },
        ] },
      },
      {
        id: "identity-4",
        title: "Review your actions",
        objective: "Run history.",
        context: "Shell history is useful for retracing actions—both your own and, when available, those of another account.",
        hint: "history",
        xp: 75,
        check: { type: "command-ran", command: "history" },
      },
    ],
  },
  {
    slug: "permissions-hardening",
    title: "Permissions & Hardening",
    subtitle: "Linux for Cybersecurity · Room 1",
    description: "Apply your permission knowledge to identify and fix a world-readable application secret.",
    path: "Linux for Cybersecurity",
    difficulty: "Easy",
    duration: "25 min",
    icon: "shield",
    tags: ["chmod", "stat", "least privilege"],
    learning: ["Interpret risky access controls", "Translate policy to octal mode", "Apply least privilege", "Verify a hardening change"],
    prerequisites: ["basic-identity"],
    tasks: [
      {
        id: "perm-1",
        title: "Inspect the exposed secret",
        objective: "Inspect permissions of /srv/app/.env using ls -l or stat.",
        context: "A deployment secret may be exposed. Establish the current state before remediation.",
        hint: "Try ls -l /srv/app/.env or stat /srv/app/.env.",
        xp: 75,
        check: { type: "history-contains", fragments: ["/srv/app/.env"] },
      },
      {
        id: "perm-2",
        title: "Remove world access",
        objective: "Set /srv/app/.env to mode 640.",
        context: "The owner needs read/write, the application group needs read, and everyone else should have no access.",
        hint: "chmod 640 /srv/app/.env",
        xp: 150,
        check: { type: "file-mode", path: "/srv/app/.env", mode: 0o640 },
      },
      {
        id: "perm-3",
        title: "Verify the fix",
        objective: "Verify the final permission state using stat.",
        context: "Security changes should be verified, not assumed.",
        hint: "stat /srv/app/.env",
        xp: 75,
        check: { type: "history-contains", fragments: ["stat", "/srv/app/.env"] },
      },
    ],
  },
  {
    slug: "log-investigation",
    title: "Log Investigation",
    subtitle: "Linux for Cybersecurity · Room 2",
    description: "Use grep and log-reading skills to isolate suspicious SSH authentication activity and an attacker source address.",
    path: "Linux for Cybersecurity",
    difficulty: "Medium",
    duration: "30 min",
    icon: "search",
    tags: ["grep", "auth.log", "SSH", "IOC"],
    learning: ["Locate authentication evidence", "Filter failed logins", "Identify repeated sources", "Confirm an IOC"],
    prerequisites: ["permissions-hardening"],
    tasks: [
      {
        id: "log-1",
        title: "Open the authentication log",
        objective: "Inspect /var/log/auth.log.",
        context: "An alert reported unusual SSH activity. Start with the host authentication evidence.",
        hint: "cat, tail, or less can inspect the file.",
        xp: 75,
        check: { type: "history-contains", fragments: ["/var/log/auth.log"] },
      },
      {
        id: "log-2",
        title: "Filter failed logins",
        objective: "Use grep to search auth.log for Failed password events.",
        context: "Reduce noise and isolate failed password attempts.",
        hint: "grep 'Failed password' /var/log/auth.log",
        xp: 125,
        check: { type: "history-contains", fragments: ["grep", "Failed", "/var/log/auth.log"] },
      },
      {
        id: "log-3",
        title: "Hunt the source IOC",
        objective: "Search auth.log for 10.10.14.23.",
        context: "The failed-login pattern points to a source address that appears repeatedly.",
        hint: "grep 10.10.14.23 /var/log/auth.log",
        xp: 150,
        check: { type: "history-contains", fragments: ["grep", "10.10.14.23", "/var/log/auth.log"] },
      },
    ],
  },
  {
    slug: "suid-hunting",
    title: "SUID Hunting",
    subtitle: "Linux for Cybersecurity · Room 3",
    description: "Search for SUID files, inspect a risky custom helper, and remove an unnecessary privilege-escalation exposure.",
    path: "Linux for Cybersecurity",
    difficulty: "Medium",
    duration: "30 min",
    icon: "file",
    tags: ["find", "SUID", "4755", "priv-esc"],
    learning: ["Understand SUID risk", "Find special-permission files", "Separate expected and custom binaries", "Remediate unnecessary SUID"],
    prerequisites: ["log-investigation"],
    tasks: [
      {
        id: "suid-1",
        title: "Enumerate SUID files",
        objective: "Use find to search /usr for SUID files.",
        context: "A hardening review flagged possible privilege-escalation exposure.",
        hint: "find /usr -perm -4000",
        xp: 150,
        check: { type: "history-contains", fragments: ["find", "/usr", "4000"] },
      },
      {
        id: "suid-2",
        title: "Inspect the custom helper",
        objective: "Inspect /usr/local/bin/backup-helper permissions.",
        context: "A custom root-owned helper appears in the SUID search results.",
        hint: "ls -l /usr/local/bin/backup-helper",
        xp: 100,
        check: { type: "history-contains", fragments: ["/usr/local/bin/backup-helper"] },
      },
      {
        id: "suid-3",
        title: "Remove unnecessary SUID",
        objective: "Set backup-helper to mode 755.",
        context: "The helper does not require elevated execution. Preserve execution while removing SUID.",
        hint: "chmod 755 /usr/local/bin/backup-helper",
        xp: 175,
        check: { type: "file-mode", path: "/usr/local/bin/backup-helper", mode: 0o755 },
      },
    ],
  },
  {
    slug: "process-response",
    title: "Process Response",
    subtitle: "Linux for Cybersecurity · Room 4",
    description: "Triage abnormal CPU usage, correlate a suspicious PID, and contain a simulated cryptominer process.",
    path: "Linux for Cybersecurity",
    difficulty: "Medium",
    duration: "25 min",
    icon: "activity",
    tags: ["ps", "grep", "PID", "kill"],
    learning: ["Review full process listings", "Spot suspicious command lines", "Correlate a PID", "Terminate an authorized malicious process"],
    prerequisites: ["suid-hunting"],
    tasks: [
      {
        id: "proc-1",
        title: "Enumerate processes",
        objective: "Run ps aux.",
        context: "Monitoring detected sustained CPU usage. Enumerate processes before acting.",
        hint: "ps aux",
        xp: 75,
        check: { type: "history-contains", fragments: ["ps", "aux"] },
      },
      {
        id: "proc-2",
        title: "Confirm the suspicious PID",
        objective: "Filter the process list for PID 31337 or kworker-update.",
        context: "One process is consuming abnormal CPU and running from /tmp.",
        hint: "ps aux | grep 31337",
        xp: 125,
        check: { type: "any", checks: [
          { type: "history-contains", fragments: ["31337"] },
          { type: "history-contains", fragments: ["kworker-update"] },
        ] },
      },
      {
        id: "proc-3",
        title: "Contain the process",
        objective: "Terminate PID 31337.",
        context: "The SOC has authorized containment after confirmation.",
        hint: "kill 31337",
        xp: 175,
        check: { type: "process-killed", pid: 31337 },
      },
    ],
  },
  {
    slug: "network-triage",
    title: "Network Triage",
    subtitle: "Linux for Cybersecurity · Room 5",
    description: "Inspect interfaces and listening sockets, then correlate an unexpected exposed port with a process.",
    path: "Linux for Cybersecurity",
    difficulty: "Medium",
    duration: "20 min",
    icon: "activity",
    tags: ["ip addr", "ss -lntp", "ports", "listeners"],
    learning: ["Inspect interfaces", "Review TCP listeners", "Correlate ports to PIDs", "Filter network output"],
    prerequisites: ["process-response"],
    tasks: [
      {
        id: "net-1",
        title: "Inspect interfaces",
        objective: "Run ip addr.",
        context: "Establish host addressing before interpreting socket exposure.",
        hint: "ip addr",
        xp: 75,
        check: { type: "history-contains", fragments: ["ip", "addr"] },
      },
      {
        id: "net-2",
        title: "Review listening sockets",
        objective: "Run ss -lntp.",
        context: "Enumerate listening TCP services with process details.",
        hint: "ss -lntp",
        xp: 100,
        check: { type: "history-contains", fragments: ["ss", "lntp"] },
      },
      {
        id: "net-3",
        title: "Isolate port 4444",
        objective: "Filter the socket listing for port 4444.",
        context: "Port 4444 is not part of the application baseline.",
        hint: "ss -lntp | grep 4444",
        xp: 150,
        check: { type: "history-contains", fragments: ["ss", "4444"] },
      },
    ],
  },
  {
    slug: "persistence-hunting",
    title: "Persistence Hunting",
    subtitle: "Linux for Cybersecurity · Room 6",
    description: "Inspect cron-based persistence, trace a hidden /tmp payload, and quarantine the scheduled task while preserving evidence.",
    path: "Linux for Cybersecurity",
    difficulty: "Hard",
    duration: "30 min",
    icon: "file",
    tags: ["cron", "persistence", "hidden files", "quarantine"],
    learning: ["Inspect cron persistence", "Trace scheduled payloads", "Recognize hidden temporary artifacts", "Quarantine while preserving evidence"],
    prerequisites: ["network-triage"],
    badge: "Linux Defender",
    tasks: [
      {
        id: "persist-1",
        title: "Review cron definitions",
        objective: "List /etc/cron.d with metadata.",
        context: "The affected host may contain scheduled persistence.",
        hint: "ls -la /etc/cron.d",
        xp: 100,
        check: { type: "history-contains", fragments: ["ls", "/etc/cron.d"] },
      },
      {
        id: "persist-2",
        title: "Trace the scheduled payload",
        objective: "Inspect /etc/cron.d/system-update.",
        context: "One cron definition does not match the normal baseline. Read the scheduled command.",
        hint: "cat /etc/cron.d/system-update",
        xp: 125,
        check: { type: "history-contains", fragments: ["cat", "/etc/cron.d/system-update"] },
      },
      {
        id: "persist-3",
        title: "Inspect the hidden payload",
        objective: "Inspect /tmp/.cache/.sync-agent.",
        context: "The cron entry points to a hidden executable under a temporary path.",
        hint: "stat /tmp/.cache/.sync-agent",
        xp: 125,
        check: { type: "history-contains", fragments: ["/tmp/.cache/.sync-agent"] },
      },
      {
        id: "persist-4",
        title: "Quarantine the cron entry",
        objective: "Move system-update to /opt/incident/quarantine.cron.",
        context: "Preserve the suspicious definition as evidence while preventing cron.d from loading it.",
        hint: "mv /etc/cron.d/system-update /opt/incident/quarantine.cron",
        xp: 200,
        check: { type: "file-exists", path: "/opt/incident/quarantine.cron" },
      },
    ],
  },
  {
    slug: "incident-capstone",
    title: "Linux Incident Response Capstone",
    subtitle: "Incident Response · Final Room",
    description: "Combine navigation, log analysis, permission review, process triage, network context, and containment in one guided incident.",
    path: "Incident Response",
    difficulty: "Hard",
    duration: "45 min",
    icon: "flag",
    tags: ["IR", "logs", "hardening", "containment"],
    learning: ["Follow an investigation workflow", "Correlate multiple evidence sources", "Apply least privilege", "Contain active malicious behavior"],
    prerequisites: ["persistence-hunting"],
    badge: "Linux Incident Responder",
    tasks: [
      {
        id: "cap-1",
        title: "Read the incident briefing",
        objective: "Navigate to /opt/incident and inspect briefing.txt.",
        context: "You are the on-call Linux responder. The coordinator left a briefing on the affected host.",
        hint: "cd /opt/incident && cat briefing.txt is common in a real shell; in this simulator run the commands separately.",
        xp: 100,
        check: { type: "all", checks: [
          { type: "cwd", path: "/opt/incident" },
          { type: "history-contains", fragments: ["briefing.txt"] },
        ] },
      },
      {
        id: "cap-2",
        title: "Confirm attacker activity",
        objective: "Search auth.log for 10.10.14.23.",
        context: "Correlate the suspected source against host authentication evidence.",
        hint: "grep 10.10.14.23 /var/log/auth.log",
        xp: 150,
        check: { type: "history-contains", fragments: ["grep", "10.10.14.23", "/var/log/auth.log"] },
      },
      {
        id: "cap-3",
        title: "Confirm the exposed service",
        objective: "Use ss and grep to investigate port 4444.",
        context: "Validate whether the suspicious process also exposed a network listener.",
        hint: "ss -lntp | grep 4444",
        xp: 150,
        check: { type: "history-contains", fragments: ["ss", "4444"] },
      },
      {
        id: "cap-4",
        title: "Protect exposed credentials",
        objective: "Set /srv/app/.env to mode 640.",
        context: "Restrict the environment file while preserving application group access.",
        hint: "chmod 640 /srv/app/.env",
        xp: 175,
        check: { type: "file-mode", path: "/srv/app/.env", mode: 0o640 },
      },
      {
        id: "cap-5",
        title: "Contain active malware",
        objective: "Terminate PID 31337.",
        context: "The malicious process has been identified and containment is authorized.",
        hint: "kill 31337",
        xp: 200,
        check: { type: "process-killed", pid: 31337 },
      },
      {
        id: "cap-6",
        title: "Write a response marker",
        objective: "Write INCIDENT-CONTAINED to /opt/incident/status.txt using redirection or tee.",
        context: "Record a simple completion marker after containment. In a real workflow this would be replaced by case documentation.",
        hint: "echo INCIDENT-CONTAINED > /opt/incident/status.txt",
        xp: 150,
        check: { type: "file-content-contains", path: "/opt/incident/status.txt", text: "INCIDENT-CONTAINED" },
      },
    ],
  },
];

export function getRoom(slug: string) {
  return rooms.find((room) => room.slug === slug);
}

export function getRoomsForPath(path: LearningPath) {
  return rooms.filter((room) => room.path === path);
}

export function isRoomComplete(room: RoomDefinition, completedTaskIds: string[]) {
  return room.tasks.every((task) => completedTaskIds.includes(task.id));
}

export function isRoomUnlocked(room: RoomDefinition, completedTaskIds: string[]) {
  if (!room.prerequisites?.length) return true;
  return room.prerequisites.every((slug) => {
    const prerequisite = getRoom(slug);
    return prerequisite ? isRoomComplete(prerequisite, completedTaskIds) : true;
  });
}

export const totalTasks = rooms.reduce((sum, room) => sum + room.tasks.length, 0);
export const totalXp = rooms.reduce((sum, room) => sum + room.tasks.reduce((s, t) => s + t.xp, 0), 0);
